### ISSUE TITLE
Cannot build docs: nonexistent hints.md file

### ISSUE THREAD

**Issue by acarrillo** [nasa/SBN-Client#1]
Hello, thank you for publishing this much-desired SBN client, my organization is excited to use it.

I wanted to start by building documentation, but the make target for `requirements.pdf` depends on the nonexistent `hints.md`. Given the name of the target I suspect this should be `requirements.md`.

Building docs by hand is not for everyone, but for those who like to do it, I had a few prerequisites: installing `pandoc`, `texlive-latex-base`, `texlive-latex-recommended`, and `texlive-latex-extra`.

Thanks again! I am sure you have a lot of TODOs ahead of you for this project, but more documentation on how to get started would be much welcome.

**Comment by the-other-james** [comment]
Thanks for finding this!

Better documentation and a demonstration project is on the todo list... feel free to open a new issue for that.
