### ISSUE TITLE
Question: reason for flight usage caveat 

### ISSUE THREAD

**Issue by tadmorgan** [nasa/SBN-Client#10]
Is there a specific limitation or flaw that is the reason for advising that this is not for flight use? Or does it reflect something more along the lines of what it was originally developed for or the level of testing that has been done to it thus far?

Thank you.

**Comment by the-other-james** [comment]
SBN-Client was not originally developed for flight use and was developed as Class E: Design Concept, Research, Technology, and General Purpose Software as per NPR 7150.2 (Appendix D defines the classes: https://nodis3.gsfc.nasa.gov/displayDir.cfm?Internal_ID=N_PR_7150_002D_&page_name=AppendixD). It was developed as part of a small, internal research and development project to prototype a concept and not as part of a flight project.

(Edited: sorry, I thought I was responding to an issue in a different repo).

**Comment by tadmorgan** [comment]
Thanks! Appreciate the quick response and totally understand that reasoning for the note.
