### ISSUE TITLE
Undefined symbols 

### ISSUE THREAD

**Issue by thenumbertwentythree** [nasa/SBN-Client#3]
Hi, I am interested in using the python interface for an SBN client. I am able to make libsbn_client.so, but when I call `sbn_load_and_init()`, I get an undefined symbol error for `Pack_Data.` Please let me know how I might fix this.

**Comment by the-other-james** [comment]
`Pack_Data` is a function defined in the SBN app. Are you building sbn_client as part of a cFS project? sbn_client is meant to be included in the cFS apps directory. [CMakeLists.txt](https://github.com/nasa/SBN-Client/blob/main/CMakeLists.txt#L5) includes the SBN headers in the build.

**Comment by thenumbertwentythree** [comment]
Thank you for quick response - I was under the impression that I could run it as a standalone. 

I moved the SBN-Client into `apps`, but I see no corresponding output when running build.sh. I also don't see `libsbn_client.so`'s presence in target/cf. Is this a correct expectation and if so, what might I need to do to fix this?

Assuming that works, should I create a separate app to put actual client source in, and if so, how do I link this library? (Newbie to cmake here) 

Finally, how do I copy over my python source file to targets/cf (so I can run it ground-side, assuming this is the right pattern of us). 

Thank you in advance for heeding these questions, I greatly appreciate it.

**Comment by the-other-james** [comment]
You can run it as standalone... but the sbn_client still needs to have SBN and cFS headers available at compile time (Pack_Data is an inline function defined in sbn_pack.h). You could copy the required headers over... but that is a pain and then you have the problem of things breaking if the versions diverge.

Did you add sbn_client to the targets.cmake file in your defs directory? The .so will be named `sbn_client.so` using the provided CMakeLists.txt.

Once that is working, I would add a new directory to your cFS apps directory for your python application. To have cFS copy the files over as part of the regular build process, you can use a CMakeLists.txt file like this:

```
# Python programs don't need to be built, so this just copies the .py file
# If you prefer to have the python byte code (.pyc),
# then you can add a command like 'python -m files' and move the .pyc files instead
project(PYTHON_TEST NONE)

set(APP_INSTALL_SUB python_exploration)
set(APP_SOURCE fsw/src/my_python_app.py ../sbn_client/fsw/python_interface/sbn_client.py)

# Create the install targets for this shared/modular app
foreach(TGT ${APP_INSTALL_LIST})
    # Copies the python file over on a 'make install' to the exe dir
    install(FILES ${APP_SOURCE} DESTINATION ${TGT}/${INSTALL_SUBDIR}/${APP_INSTALL_SUB})
endforeach()
```

That will copy the specified files (my_python_app.py and sbn_client.py) into cf/python_exploration/ for each of your targets.

**Comment by the-other-james** [comment]
Ah, sorry, I forgot that we also included a [Makefile](https://github.com/nasa/SBN-Client/blob/main/Makefile)... if you are using that then I think the first step is to make sure that the includes are set up correctly (like `SBN_INC` and `PSP_BSP_INC`). I usually just integrate into the cFS build since that takes care of a lot of this automatically.

If you use the Makefile approach, then you would have to copy the files you want moved manually.

**Comment by the-other-james** [comment]
My guess would be you have a mix of 32-bit and 64-bit compiled code. You can check by using the `file` command on each executable/so. I would check the main cFS executable (core-cpu1) and sbn_client.so. They can be either 32-bit or 64-bit, but they can not be mixed.

It looks like the libc you are using is 64-bit (`x86_64`) so you shouldn't have any problems with 64-bit builds. If you want cFS to build as 32-bit, then you may have install a 32-bit toolchain (although I think newer gnu toolchains include 32-bit support).

**Comment by the-other-james** [comment]
Closing since there has been no response in a few months
