### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by blueed9696** [nasa/SBN-Client#8]
cFS/apps/SBN_Client/fsw/src/sbn_client.h:20:10: fatal error: sbn_interfaces.h: No such file or directory
   20 | #include "sbn_interfaces.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[7]: *** [apps/SBN_Client/CMakeFiles/sbn_client.dir/build.make:76: apps/SBN_Client/CMakeFiles/sbn_client.dir/fsw/src/sbn_client.c.o] Error 1
make[6]: *** [CMakeFiles/Makefile2:2089: apps/SBN_Client/CMakeFiles/sbn_client.dir/all] Error 2
make[5]: *** [Makefile:146: all] Error 2
make[4]: *** [CMakeFiles/native_default_cpu1-all.dir/build.make:70: CMakeFiles/native_default_cpu1-all] Error 2
make[3]: *** [CMakeFiles/Makefile2:518: CMakeFiles/native_default_cpu1-all.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:232: CMakeFiles/mission-all.dir/rule] Error 2
make[1]: *** [Makefile:179: mission-all] Error 2
make: *** [Makefile:119: all] Error 2

Will this be a right header file to import? Where can I find it?

**Comment by the-other-james** [comment]
That file comes from SBN: https://github.com/nasa/SBN/blob/main/fsw/platform_inc/sbn_interfaces.h

**Comment by blueed9696** [comment]
Thank you! I didn't expect this fast.
